Insert Into DrugInfo (DrugID, Name, GenericName, DrugDescription) VALUES
(1, 'Warfarin', 'Warfarin Sodium', 'An anticoagulant used to prevent blood clots.'),
(2, 'Aspirin', 'Acetylsalicylic Acid', 'A nonsteroidal anti-inflammatory drug (NSAID) used to reduce pain, fever, and inflammation.'),
(3, 'Cipro', 'Ciprofloxacin', 'An antibiotic used to treat various bacterial infections.'),
(4, 'Lipitor', 'Atorvastatin', 'A statin used to lower cholesterol levels.'),
(5, 'Crestor', 'Rosuvastatin', 'A statin used to lower cholesterol levels.'),
(6, 'Celexa', 'Citalopram', 'An antidepressant used to treat depression and anxiety disorders.'),
(7, 'Metformin', 'Metformin', 'An antidiabetic medication used to control blood sugar levels in type 2 diabetes.'),
(8, 'Lisinopril', 'Lisinopril', 'An ACE inhibitor used to treat high blood pressure and heart failure.'),
(9, 'Prilosec', 'Omeprazole', 'A proton pump inhibitor used to treat gastroesophageal reflux disease (GERD).'),
(10, 'Levothyroxine', 'Levothyroxine Sodium', 'A thyroid hormone replacement therapy for hypothyroidism.'),
(11, 'Metoprolol', 'Metoprolol Tartrate', 'A beta blocker used to treat high blood pressure and heart conditions.'),
(12, 'Amlodipine', 'Amlodipine Besylate', 'A calcium channel blocker used to treat high blood pressure and angina.'),
(13, 'Zocor', 'Simvastatin', 'A statin used to lower cholesterol levels.'),
(14, 'Plavix', 'Clopidogrel Bisulfate', 'An antiplatelet medication used to prevent blood clots.'),
(15, 'Gabapentin', 'Gabapentin', 'An anticonvulsant used to treat nerve pain and seizures.'),
(16, 'Hydrochlorothiazide', 'Hydrochlorothiazide', 'A diuretic used to treat high blood pressure and fluid retention.'),
(17, 'Lasix', 'Furosemide', 'A loop diuretic used to treat fluid retention and high blood pressure.'),
(18, 'Albuterol', 'Albuterol Sulfate', 'A bronchodilator used to treat asthma and other respiratory conditions.'),
(19, 'Prednisone', 'Prednisone', 'A corticosteroid used to reduce inflammation and suppress the immune system.'),
(20, 'Zoloft', 'Sertraline Hydrochloride', 'An antidepressant used to treat depression, anxiety, and OCD.'),
(21, 'Prozac', 'Fluoxetine Hydrochloride', 'An antidepressant used to treat depression, anxiety, and OCD.'),
(22, 'Cymbalta', 'Duloxetine Hydrochloride', 'An antidepressant used to treat depression and anxiety disorders.'),
(23, 'Singulair', 'Montelukast Sodium', 'A leukotriene receptor antagonist used to prevent asthma attacks and allergic rhinitis.'),
(24, 'Flomax', 'Tamsulosin Hydrochloride', 'An alpha blocker used to treat benign prostatic hyperplasia (BPH).'),
(25, 'Ceftriaxone', 'Ceftriaxone Sodium', 'A cephalosporin antibiotic used to treat various bacterial infections.'),
(26, 'Zithromax', 'Azithromycin Dihydrate', 'A macrolide antibiotic used to treat bacterial infections.'),
(27, 'Metronidazole', 'Metronidazole', 'An antibiotic used to treat various infections including bacterial vaginosis and certain types of diarrhea.'),
(28, 'Insulin Glargine', 'Insulin Glargine', 'A long-acting insulin used to control blood sugar levels in diabetes.'),
(29, 'Insulin Lispro', 'Insulin Lispro', 'A rapid-acting insulin used to control blood sugar levels in diabetes.'),
(30, 'Klonopin', 'Clonazepam', 'A benzodiazepine used to treat panic disorder and seizures.'),
(31, 'Ativan', 'Lorazepam', 'A benzodiazepine used to treat anxiety disorders.'),
(32, 'Valium', 'Diazepam', 'A benzodiazepine used to treat anxiety, muscle spasms, and seizures.');