-- SQL script to create Drugs and DrugInteractions tables, insert initial data, and query interactions
-- Insert initial data into Drugs and DrugInteractions tables
-- Insert Drugs
INSERT INTO Drugs (Name, GenericName, DrugClass) VALUES
('Warfarin', 'Warfarin Sodium', 'Anticoagulant'),
('Aspirin', 'Acetylsalicylic Acid', 'NSAID'),
('Ciprofloxacin', 'Ciprofloxacin', 'Antibiotic'),
('Atorvastatin', 'Atorvastatin', 'Statin'),
('Rosuvastatin', 'Rosuvastatin', 'Statin'),
('Citalopram', 'Citalopram', 'Antidepressant'),
('Metformin', 'Metformin', 'Antidiabetic'),
('Lisinopril', 'Lisinopril', 'ACE Inhibitor'),
('Omeprazole', 'Omeprazole', 'Proton Pump Inhibitor'),
('Levothyroxine', 'Levothyroxine Sodium', 'Thyroid Hormone'),
('Metoprolol', 'Metoprolol Tartrate', 'Beta Blocker'),
('Amlodipine', 'Amlodipine Besylate', 'Calcium Channel Blocker'),
('Zocor', 'Simvastatin', 'Statin'),
('Clopidogrel', 'Clopidogrel Bisulfate', 'Antiplatelet'),
('Gabapentin', 'Gabapentin', 'Anticonvulsant'),
('Hydrochlorothiazide', 'Hydrochlorothiazide', 'Diuretic'),
('Furosemide', 'Furosemide', 'Loop Diuretic'),
('Albuterol', 'Albuterol Sulfate', 'Bronchodilator'),
('Prednisone', 'Prednisone', 'Corticosteroid'),
('Zoloft', 'Sertraline Hydrochloride', 'Antidepressant'),
('Prozac', 'Fluoxetine Hydrochloride', 'Antidepressant'),
('Duloxetine', 'Duloxetine Hydrochloride', 'Antidepressant'),
('Ranitidine', 'Ranitidine Hydrochloride', 'H2 Antagonist'),
('Montelukast', 'Montelukast Sodium', 'Leukotriene Receptor Antagonist'),
('Flomax', 'Tamsulosin Hydrochloride', 'Alpha Blocker'),
('Ceftriaxone', 'Ceftriaxone Sodium', 'Cephalosporin Antibiotic'),
('Zithromax', 'Azithromycin Dihydrate', 'Macrolide Antibiotic'),
('Metronidazole', 'Metronidazole', 'Antibiotic'),
('Insulin Glargine', 'Insulin Glargine', 'Long-Acting Insulin');
