-- SQL script to create Drugs and DrugInteractions tables, insert initial data, and query interactions
-- Insert initial data into Drugs and DrugInteractions tables
-- Insert Drugs
INSERT INTO Drugs (Name, GenericName, DrugClass) VALUES
('Warfarin', 'Warfarin Sodium', 'Anticoagulant'),
('Aspirin', 'Acetylsalicylic Acid', 'NSAID'),
('Cipro', 'Ciprofloxacin', 'Antibiotic'),
('Lipitor', 'Atorvastatin', 'Statin'),
('Crestor', 'Rosuvastatin', 'Statin'),
('Celexa', 'Citalopram', 'Antidepressant'),
('Metformin', 'Metformin', 'Antidiabetic'),
('Lisinopril', 'Lisinopril', 'ACE Inhibitor'),
('Prilosec', 'Omeprazole', 'Proton Pump Inhibitor'),
('Levothyroxine', 'Levothyroxine Sodium', 'Thyroid Hormone'),
('Metoprolol', 'Metoprolol Tartrate', 'Beta Blocker'),
('Amlodipine', 'Amlodipine Besylate', 'Calcium Channel Blocker'),
('Zocor', 'Simvastatin', 'Statin'),
('Plavix', 'Clopidogrel Bisulfate', 'Antiplatelet'),
('Gabapentin', 'Gabapentin', 'Anticonvulsant'),
('Hydrochlorothiazide', 'Hydrochlorothiazide', 'Diuretic'),
('Lasix', 'Furosemide', 'Loop Diuretic'),
('Albuterol', 'Albuterol Sulfate', 'Bronchodilator'),
('Prednisone', 'Prednisone', 'Corticosteroid'),
('Zoloft', 'Sertraline Hydrochloride', 'Antidepressant'),
('Prozac', 'Fluoxetine Hydrochloride', 'Antidepressant'),
('Cymbalta', 'Duloxetine Hydrochloride', 'Antidepressant'),
('Singulair', 'Montelukast Sodium', 'Leukotriene Receptor Antagonist'),
('Flomax', 'Tamsulosin Hydrochloride', 'Alpha Blocker'),
('Ceftriaxone', 'Ceftriaxone Sodium', 'Cephalosporin Antibiotic'),
('Zithromax', 'Azithromycin Dihydrate', 'Macrolide Antibiotic'),
('Metronidazole', 'Metronidazole', 'Antibiotic'),
('Insulin Glargine', 'Insulin Glargine', 'Long-Acting Insulin'),
('Insulin Lispro', 'Insulin Lispro', 'Rapid-Acting Insulin'),
('Klonopin', 'Clonazepam', 'Benzodiazepine'),
('Ativan', 'Lorazepam', 'Benzodiazepine'),
('Valium', 'Diazepam', 'Benzodiazepine'),
('Xanax', 'Alprazolam', 'Benzodiazepine'),
('Oxycodone', 'Oxycodone Hydrochloride', 'Opioid Analgesic'),
('Norco', 'Hydrocodone-Acetaminophen', 'Opioid Analgesic'),
('Tramadol', 'Tramadol Hydrochloride', 'Opioid Analgesic'),
('Lyrica', 'Pregabalin', 'Anticonvulsant'),
('Ambien', 'Zolpidem Tartrate', 'Sedative-Hypnotic'),
('Wellbutrin', 'Bupropion Hydrochloride', 'Antidepressant'),
('Remeron', 'Mirtazapine', 'Antidepressant'),
('Seroquel', 'Quetiapine Fumarate', 'Antipsychotic'),
('Risperdal', 'Risperidone', 'Antipsychotic'),
('Abilify', 'Aripiprazole', 'Antipsychotic'),
('Lithium Carbonate', 'Lithium Carbonate', 'Mood Stabilizer'),
('Depakote', 'Divalproex Sodium', 'Anticonvulsant/Mood Stabilizer'),
('Adderall', 'Amphetamine-Dextroamphetamine', 'Stimulant'),
('Concerta', 'Methylphenidate', 'Stimulant'),
('Vyvanse', 'Lisdexamfetamine Dimesylate', 'Stimulant'),
('Zyrtec', 'Cetirizine Hydrochloride', 'Antihistamine'),
('Claritin', 'Loratadine', 'Antihistamine'),
('Allegra', 'Fexofenadine Hydrochloride', 'Antihistamine'),
('Flonase', 'Fluticasone Propionate', 'Corticosteroid Nasal Spray'),
('Nasonex', 'Mometasone Furoate', 'Corticosteroid Nasal Spray'),
('Xarelto', 'Rivaroxaban', 'Anticoagulant'),
('Eliquis', 'Apixaban', 'Anticoagulant'),
('Pradaxa', 'Dabigatran Etexilate', 'Anticoagulant'),
('Trulicity', 'Dulaglutide', 'GLP-1 Receptor Agonist'),
('Januvia', 'Sitagliptin Phosphate', 'DPP-4 Inhibitor'),
('Farxiga', 'Dapagliflozin', 'SGLT2 Inhibitor'),
('Invokana', 'Canagliflozin', 'SGLT2 Inhibitor'),
('Actos', 'Pioglitazone Hydrochloride', 'Thiazolidinedione'),
('Glucophage', 'Metformin Hydrochloride', 'Biguanide'),
('Lexapro', 'Escitalopram Oxalate', 'Antidepressant'),
('Pristiq', 'Desvenlafaxine Succinate', 'Antidepressant'),
('Effexor XR', 'Venlafaxine Hydrochloride', 'Antidepressant'),
('Buspar', 'Buspirone Hydrochloride', 'Anxiolytic'),
('Zanaflex', 'Tizanidine Hydrochloride', 'Muscle Relaxant'),
('Flexeril', 'Cyclobenzaprine Hydrochloride', 'Muscle Relaxant'),
('Robaxin', 'Methocarbamol', 'Muscle Relaxant'),
('Celebrex', 'Celecoxib', 'NSAID'),
('Voltaren', 'Diclofenac Sodium', 'NSAID'),
('Lidocaine Patch', 'Lidocaine', 'Topical Analgesic'),
('Bactrim', 'Trimethoprim-Sulfamethoxazole', 'Antibiotic'),
('Augmentin', 'Amoxicillin-Clavulanate Potassium', 'Antibiotic'),
('Cipro HC Otic', 'Ciprofloxacin-Hydrocortisone', 'Otic Antibiotic'),
('Lotrel', 'Amlodipine-Benazepril', 'Combination Antihypertensive'),
('Combivent', 'Ipratropium-Albuterol', 'Bronchodilator Combination'),
('Symbicort', 'Budesonide-Formoterol', 'Corticosteroid-Bronchodilator Combination'),
('Advair Diskus', 'Fluticasone-Salmeterol', 'Corticosteroid-Bronchodilator Combination'),
('Singulair Chewable', 'Montelukast Sodium Chewable', 'Leukotriene Receptor Antagonist'),
('Zostavax', 'Zoster Vaccine Live', 'Vaccine'),
('FluMist', 'Influenza Vaccine Live', 'Vaccine'),
('Gardasil', 'Human Papillomavirus Vaccine', 'Vaccine'),
('Prevnar 13', 'Pneumococcal Conjugate Vaccine', 'Vaccine'),
('Hepatitis B Vaccine', 'Hepatitis B Vaccine Recombinant', 'Vaccine');