-- Insert Interactions
INSERT INTO DrugInteractions (Drug1ID, Drug2ID, Severity, Description, Mechanism, Management) VALUES
((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Warfarin', 'Aspirin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Warfarin', 'Aspirin')),
 'High',
 'Increased bleeding risk',
 'Platelet inhibition + anticoagulation',
 'Avoid combination or monitor bleeding time'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Zocor')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Zocor')),
 'Moderate',
 'Increased statin levels',
 'CYP3A4 inhibition',
 'Use lower statin dose or alternative antibiotic'),

 ((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Metformin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Metformin')),
 'Moderate',
 'Increased risk of lactic acidosis',
 'Cipro may impair renal function',
 'Monitor renal function and consider alternative antibiotic'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Warfarin', 'Cipro')),
(SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Warfarin', 'Cipro')),
 'High',
 'Increased bleeding risk',
 'Cipro may displace warfarin from protein binding sites',
 'Monitor INR closely and adjust warfarin dose as needed'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Warfarin', 'Metformin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Warfarin', 'Metformin')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Aspirin', 'Metformin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Aspirin', 'Metformin')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Aspirin', 'Cipro')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Aspirin', 'Cipro')),
 'Moderate',
 'Increased risk of gastrointestinal bleeding',
 'Both drugs can cause GI irritation',
 'Monitor for signs of GI bleeding and consider alternatives if necessary'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Aspirin', 'Zocor')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Aspirin', 'Zocor')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Prozac', 'Abilify')),
(SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Prozac', 'Abilify')),
 'Moderate',
 'Increased risk of serotonin syndrome',
 'Both drugs increase serotonin levels',
 'Monitor for symptoms of serotonin syndrome and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Prozac')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Prozac')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Prozac')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Prozac')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Zocor', 'Prozac')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Zocor', 'Prozac')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Zoloft', 'Abilify')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Zoloft', 'Abilify')),
 'Moderate',
 'Increased risk of serotonin syndrome',
 'Both drugs increase serotonin levels',
 'Monitor for symptoms of serotonin syndrome and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Zoloft')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Zoloft')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Zoloft')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Zoloft')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Zocor', 'Zoloft')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Zocor', 'Zoloft')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Lipitor')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Lipitor')),
 'Moderate',
 'Increased risk of statin-related side effects',
 'Cipro may increase statin levels',
 'Consider alternative antibiotics or monitor for statin side effects'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Lipitor', 'Metformin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Lipitor', 'Metformin')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Crestor')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Crestor')),
 'Moderate',
 'Increased risk of statin-related side effects',
 'Cipro may increase statin levels',
 'Consider alternative antibiotics or monitor for statin side effects'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Crestor', 'Metformin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Crestor', 'Metformin')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Gabapentin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Gabapentin')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Gabapentin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Gabapentin')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Hydrochlorothiazide')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Hydrochlorothiazide')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Hydrochlorothiazide')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Hydrochlorothiazide')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Lasix')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Lasix')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Lasix')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Lasix')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Albuterol')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Albuterol')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Albuterol')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Albuterol')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

 ((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Prednisone')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Prednisone')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Prednisone')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Prednisone')),
 'Low',
 'No significant interaction',
 'NULL', 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Norco')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Norco')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Tramadol')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Tramadol')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Lyrica')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Lyrica')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs are anticonvulsants with similar effects',
 'Monitor for sedation and consider dose adjustments'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Ambien')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Ambien')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Wellbutrin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Wellbutrin')),
 'Moderate',
 'Increased risk of seizures',
 'Both drugs can lower seizure threshold',
 'Monitor for seizure activity and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Remeron')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Remeron')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Seroquel')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Seroquel')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Risperdal')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Risperdal')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Abilify')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Abilify')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Lithium Carbonate')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Lithium Carbonate')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Depakote')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Depakote')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Adderall')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Adderall')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Concerta')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Concerta')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Vyvanse')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Vyvanse')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Zyrtec')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Zyrtec')),
 'Low',
 'No significant interaction',
  'NULL',
 'No special management required'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Claritin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Claritin')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Allegra')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Allegra')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),
 
((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Flonase')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Flonase')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Xarelto')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Xarelto')),
 'Moderate',
 'Increased risk of bleeding',
 'Gabapentin may increase bleeding risk with anticoagulants',
 'Monitor for signs of bleeding and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Eliquis')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Eliquis')),
 'Moderate',
 'Increased risk of bleeding',
 'Gabapentin may increase bleeding risk with anticoagulants',
 'Monitor for signs of bleeding and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Pradaxa')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Pradaxa')),
 'Moderate',
 'Increased risk of bleeding',
 'Gabapentin may increase bleeding risk with anticoagulants',
 'Monitor for signs of bleeding and consider dose adjustments'),  

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Trulicity')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Trulicity')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Insulin Glargine')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Insulin Glargine')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Insulin Lispro')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Insulin Lispro')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Klonopin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Klonopin')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Ativan')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Ativan')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Valium')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Valium')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'), 

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Xanax')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Xanax')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Oxycodone')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Oxycodone')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Fentanyl')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Gabapentin', 'Fentanyl')),
 'Moderate',
 'Increased risk of CNS depression',
 'Both drugs can cause sedation',
 'Monitor for sedation and consider dose adjustments');

 --Remove Duplicate Interactions
WITH Duplicates AS (
  SELECT *,
    ROW_NUMBER() OVER (
      PARTITION BY Drug1ID, Drug2ID, Severity, Description, Mechanism, Management
      ORDER BY InteractionID
    ) AS rn
  FROM DrugInteractions
)
DELETE FROM Duplicates WHERE rn > 1;