-- Insert Interactions
INSERT INTO DrugInteractions (Drug1ID, Drug2ID, Severity, Description, Mechanism, Management) VALUES
/*((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Warfarin', 'Aspirin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Warfarin', 'Aspirin')),
 'High',
 'Increased bleeding risk',
 'Platelet inhibition + anticoagulation',
 'Avoid combination or monitor bleeding time'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Zocor')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Zocor')),
 'Moderate',
 'Increased statin levels',
 'CYP3A4 inhibition',
 'Use lower statin dose or alternative antibiotic'),

 ((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Metformin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Metformin')),
 'Moderate',
 'Increased risk of lactic acidosis',
 'Cipro may impair renal function',
 'Monitor renal function and consider alternative antibiotic'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Warfarin', 'Cipro')),
(SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Warfarin', 'Cipro')),
 'High',
 'Increased bleeding risk',
 'Cipro may displace warfarin from protein binding sites',
 'Monitor INR closely and adjust warfarin dose as needed'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Warfarin', 'Metformin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Warfarin', 'Metformin')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Aspirin', 'Metformin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Aspirin', 'Metformin')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Aspirin', 'Cipro')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Aspirin', 'Cipro')),
 'Moderate',
 'Increased risk of gastrointestinal bleeding',
 'Both drugs can cause GI irritation',
 'Monitor for signs of GI bleeding and consider alternatives if necessary'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Aspirin', 'Zocor')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Aspirin', 'Zocor')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Prozac', 'Abilify')),
(SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Prozac', 'Abilify')),
 'Moderate',
 'Increased risk of serotonin syndrome',
 'Both drugs increase serotonin levels',
 'Monitor for symptoms of serotonin syndrome and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Prozac')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Prozac')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Prozac')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Prozac')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Zocor', 'Prozac')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Zocor', 'Prozac')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Zoloft', 'Abilify')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Zoloft', 'Abilify')),
 'Moderate',
 'Increased risk of serotonin syndrome',
 'Both drugs increase serotonin levels',
 'Monitor for symptoms of serotonin syndrome and consider dose adjustments'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Zoloft')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Zoloft')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Zoloft')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Metformin', 'Zoloft')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Zocor', 'Zoloft')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Zocor', 'Zoloft')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),*/

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Lipitor')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Lipitor')),
 'Moderate',
 'Increased risk of statin-related side effects',
 'Cipro may increase statin levels',
 'Consider alternative antibiotics or monitor for statin side effects'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Lipitor', 'Metformin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Lipitor', 'Metformin')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Crestor')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Cipro', 'Crestor')),
 'Moderate',
 'Increased risk of statin-related side effects',
 'Cipro may increase statin levels',
 'Consider alternative antibiotics or monitor for statin side effects'),

((SELECT MIN(DrugID) FROM Drugs WHERE Name IN ('Crestor', 'Metformin')),
 (SELECT MAX(DrugID) FROM Drugs WHERE Name IN ('Crestor', 'Metformin')),
 'Low',
 'No significant interaction',
 'NULL',
 'No special management required');
